import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main className="container mx-auto h-[calc(100vh)-7rem] p-50 flex justify-center items-center align-middle">
          {children}
        </main>
      </body>
    </html>
  );
}
